extensions:
  commerce/backend-ui/1:
    $include: src/commerce-backend-ui-1/ext.config.yaml

application:
  runtimeManifest:
    packages:
      commerce:
        license: Apache-2.0
        actions:
          $include: actions/commerce/actions.config.yaml
