inputs:
  AIO_COMMERCE_API_BASE_URL: $COMMERCE_BASE_URL

  AIO_COMMERCE_AUTH_IMS_CLIENT_ID: $OAUTH_CLIENT_ID
  AIO_COMMERCE_AUTH_IMS_CLIENT_SECRETS: $OAUTH_CLIENT_SECRETS
  AIO_COMMERCE_AUTH_IMS_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
  AIO_COMMERCE_AUTH_IMS_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
  AIO_COMMERCE_AUTH_IMS_SCOPES: $OAUTH_SCOPES
  AIO_COMMERCE_AUTH_IMS_ORG_ID: $OAUTH_IMS_ORG_ID

  AIO_COMMERCE_AUTH_INTEGRATION_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
  AIO_COMMERCE_AUTH_INTEGRATION_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
  AIO_COMMERCE_AUTH_INTEGRATION_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
  AIO_COMMERCE_AUTH_INTEGRATION_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET

  BACKEND_BASE_URL: $BACKEND_BASE_URL
  BACKEND_ACCESS_TOKEN: $BACKEND_ACCESS_TOKEN

actions:
  publisher:
    function: publisher/index.js
    runtime: nodejs:20

  run-action:
    function: run-action/index.js
    runtime: nodejs:20
