registration:
  function: registration/index.js
  web: yes
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
    BACKOFFICE_BASE_URL: $BACKOFFICE_BASE_URL
  annotations:
    require-adobe-auth: true
mass-action:
  function: mass-action/index.js
  web: yes
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
